name: "Automated GitHub Release"

on:
  create:
    tags:
      - "v*"  # Ce workflow se déclenche UNIQUEMENT quand un tag est créé sur GitHub

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Action
        run: npm run build  # Compilation de l'action TypeScript

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: "🚀 Nouvelle version publiée automatiquement sur GitHub !"
          draft: false
          prerelease: false
          files: |
            dist/index.js
        env:
            GH_ACTION: ${{ secrets.GH_ACTION }}
